### ISSUE TITLE
Dependency isn't compatible with IE11

### ISSUE THREAD

**Issue by downeyfe** [jekrb/state-copy#1]
The dependency [copy-text-to-clipboard](https://github.com/sindresorhus/copy-text-to-clipboard) is incompatible with IE11 because it uses arrow functions. The owner has made it clear that they don't want to support non-modern browsers and so they've declined PRs to change this. This means that people who do need to support IE11 can't use state-copy without additional tweaking (and in my case I'm using it as a dependency from another library, [choo-devtools](https://github.com/choojs/choo-devtools)). I found a [fork of copy-text-to-clipboard](https://github.com/deliriousrhino/copy-text-to-clipboard) that is up to date with the original and only has some small changes - to remove the arrow function and lets/consts. 
Have you considered using another library for the clipboard functionality, perhaps the one above?

**Comment by jekrb** [comment]
Hey @downeyfe, thanks for spotting this issue! I'd totally use the fork to help IE11 users.

Would you be willing to open a pull request, switching copy-text-to-clipboard with the fork?

**Comment by downeyfe** [comment]
Sure, and thanks for the quick response!

**Comment by jekrb** [comment]
@downeyfe this published on npm now as state-copy@1.0.4, thanks again!
